# Generated by Django 6.0.7 on 2026-08-07 18:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_groups', to='projects.project')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('stacktrace', models.TextField(blank=True, default='')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('fatal', 'Fatal')], default='error', max_length=16)),
                ('environment', models.CharField(blank=True, default='', max_length=32)),
                ('service', models.CharField(blank=True, default='', max_length=64)),
                ('endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('request_method', models.CharField(blank=True, default='', max_length=16)),
                ('user_id', models.CharField(blank=True, default='', max_length=128)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.errorgroup')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='errorgroup',
            constraint=models.UniqueConstraint(fields=('project', 'fingerprint'), name='uniq_errorgroup_project_fingerprint'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['project', 'created_at'], name='idx_event_project_created'),
        ),
    ]
