# Generated by Django 6.0.7 on 2026-08-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='status',
            field=models.CharField(choices=[('dispatched', 'Dispatched'), ('failed', 'Failed')], default='dispatched', max_length=16),
        ),
    ]
