# Generated by Django 6.0.7 on 2026-08-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='events_per_minute',
            field=models.PositiveIntegerField(default=1000, help_text='Per-project ingestion cap (events/minute). Enforced by EventPerKeyRateThrottle; overrides the global EVENT_THROTTLE_KEY.'),
        ),
    ]
