# Generated by Django 6.0.7 on 2026-08-11 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(help_text='Encrypted at rest via django-cryptography.', max_length=512)),
                ('team_name', models.CharField(blank=True, default='', max_length=120)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_integration', to='organizations.organization')),
            ],
            options={
                'ordering': ['-connected_at'],
            },
        ),
    ]
