# Generated by Django 6.0.7 on 2026-08-11 17:11

import apps.integrations.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackintegration',
            name='access_token',
            field=apps.integrations.fields.EncryptedCharField(help_text='Encrypted at rest (Fernet, key derived from SECRET_KEY).', max_length=512),
        ),
    ]
