# Generated by Django 6.0.7 on 2026-08-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('key_rotated', 'API key rotated'), ('member_removed', 'Member removed'), ('incident_resolved', 'Incident resolved'), ('incidents_bulk_updated', 'Incidents bulk updated')], max_length=32),
        ),
    ]
