# Generated by Django 6.0.7 on 2026-08-05 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0002_timelineentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.TextField(blank=True, default='')),
                ('suggested_fix', models.TextField(blank=True, default='')),
                ('confidence', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('model_used', models.CharField(blank=True, default='', max_length=128)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['incident', '-created_at'], name='idx_ai_analysis_incident_created')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('incident',), name='uniq_ai_analysis_pending_incident')],
            },
        ),
    ]
