# Generated by Django 6.0.7 on 2026-08-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aianalysis',
            new_name='idx_ai_analysis_incident',
            old_name='idx_ai_analysis_incident_created',
        ),
    ]
