# Generated by Django 6.0.7 on 2026-09-05 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_events_per_minute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('target_pct', models.DecimalField(decimal_places=2, help_text='The success-rate target (e.g. 99.90 means 99.9% uptime).', max_digits=5)),
                ('window_days', models.PositiveIntegerField(default=30, help_text='Rolling window the error budget is measured over.')),
                ('error_query', models.JSONField(default=dict, help_text='Filter applied to events when counting bad events: {severity?, service?}.')),
                ('alert_threshold_pct', models.DecimalField(decimal_places=2, default=25, help_text='Percentage of budget remaining below which a breach alert is fired (e.g. 25 means fire when 75% of the budget is consumed).', max_digits=5)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slos', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLOBudgetSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('bad_events', models.PositiveIntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=4, default=0, help_text='(1 - bad/total) as a fraction; 0 when total=0.', max_digits=7)),
                ('budget_total', models.DecimalField(decimal_places=4, default=0, help_text='Allowed bad events in the window: total * (1 - target).', max_digits=12)),
                ('budget_remaining_pct', models.DecimalField(decimal_places=2, default=0, help_text='0-100; 100 = full budget remaining, 0 = exhausted.', max_digits=7)),
                ('burn_rate_1h', models.DecimalField(decimal_places=4, default=0, help_text='Bad-event rate per hour over the last hour.', max_digits=12)),
                ('burn_rate_6h', models.DecimalField(decimal_places=4, default=0, help_text='Bad-event rate per hour over the last 6 hours.', max_digits=12)),
                ('burn_rate_24h', models.DecimalField(decimal_places=4, default=0, help_text='Bad-event rate per hour over the last 24 hours.', max_digits=12)),
                ('burn_rate_72h', models.DecimalField(decimal_places=4, default=0, help_text='Bad-event rate per hour over the last 72 hours.', max_digits=12)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('exhausted', 'Exhausted')], default='healthy', max_length=16)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('slo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='slos.slo')),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='SLOBreachAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical'), ('exhausted', 'Exhausted')], max_length=16)),
                ('budget_remaining_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('message', models.CharField(max_length=255)),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slo_breach_alerts', to=settings.AUTH_USER_MODEL)),
                ('slo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breach_alerts', to='slos.slo')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breach_alerts', to='slos.slobudgetsnapshot')),
            ],
            options={
                'ordering': ['-fired_at'],
            },
        ),
        migrations.AddIndex(
            model_name='slo',
            index=models.Index(fields=['project'], name='idx_slo_project'),
        ),
        migrations.AddIndex(
            model_name='slobudgetsnapshot',
            index=models.Index(fields=['slo', '-evaluated_at'], name='idx_slosnap_slo_evaluated'),
        ),
        migrations.AddIndex(
            model_name='slobreachalert',
            index=models.Index(fields=['slo', 'kind', 'fired_at'], name='idx_sloalert_slo_kind'),
        ),
    ]
