# Generated by Django 6.0.7 on 2026-09-05 15:30

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def merge_duplicate_open_incidents(apps, schema_editor):
    """Merge pre-constraint duplicate OPEN incidents (Phase 5E).

    Before ``uniq_open_incident_per_group`` existed, concurrent first-ingests
    could each create an OPEN incident for the same group. Fold extras into
    the earliest one: repoint its timeline entries and AI analyses, then
    delete the redundant rows so the constraint applies cleanly.
    """
    Incident = apps.get_model("incidents", "Incident")
    TimelineEntry = apps.get_model("incidents", "TimelineEntry")
    AIAnalysis = apps.get_model("ai", "AIAnalysis")

    dup_group_ids = (
        Incident.objects.filter(status="open")
        .values("error_group_id")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
        .values_list("error_group_id", flat=True)
    )
    for group_id in dup_group_ids:
        ordered = list(
            Incident.objects.filter(
                error_group_id=group_id, status="open"
            ).order_by("created_at", "id")
        )
        keeper, extras = ordered[0], ordered[1:]
        extra_ids = [inc.id for inc in extras]
        TimelineEntry.objects.filter(incident_id__in=extra_ids).update(
            incident_id=keeper.id
        )
        keeper_has_pending = AIAnalysis.objects.filter(
            incident_id=keeper.id, status="pending"
        ).exists()
        for analysis in AIAnalysis.objects.filter(
            incident_id__in=extra_ids
        ).order_by("created_at", "id"):
            # The partial unique allows one pending row per incident — a
            # conflicting extra pending row is dropped (it represents an
            # in-flight task, never a completed analysis).
            if analysis.status == "pending" and keeper_has_pending:
                analysis.delete()
            else:
                analysis.incident_id = keeper.id
                analysis.save(update_fields=["incident"])
                if analysis.status == "pending":
                    keeper_has_pending = True
        Incident.objects.filter(id__in=extra_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("events", "0002_event_breadcrumbs"),
        ("incidents", "0001_initial"),
        ("projects", "0002_project_events_per_minute"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            merge_duplicate_open_incidents, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="incident",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("error_group",),
                name="uniq_open_incident_per_group",
            ),
        ),
    ]
