# Generated by Django 6.0.7 on 2026-08-16 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('only_assigned_to_me', models.BooleanField(default=False, help_text='Only notify me about incidents assigned to me; in-org activity on other incidents is silenced.')),
                ('notify_on_new_incidents', models.BooleanField(default=True)),
                ('notify_on_status_changes', models.BooleanField(default=True)),
                ('notify_on_comments', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('incident_created', 'Incident created'), ('incident_assigned', 'Incident assigned'), ('incident_updated', 'Incident updated'), ('incident_commented', 'Incident commented'), ('incident_resolved', 'Incident resolved'), ('system', 'System')], max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='incidents.incident')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='idx_notif_recipient_read'), models.Index(fields=['recipient', 'created_at'], name='idx_notif_recipient_created')],
            },
        ),
    ]
